# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instagramInfoApp.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

import instaloader
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1300, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 320, 391, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.usernameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameInput.setObjectName("usernameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameInput)
        self.uNameBtn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.uNameBtn.setObjectName("uNameBtn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uNameBtn)
        self.usernamelabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.usernamelabel.setObjectName("usernamelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernamelabel)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(430, 0, 861, 301))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.MediaCount = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.MediaCount.setObjectName("MediaCount")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.MediaCount)
        self.mediaCount = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.mediaCount.setObjectName("mediaCount")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mediaCount)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.isPrivate = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.isPrivate.setReadOnly(True)
        self.isPrivate.setObjectName("isPrivate")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.isPrivate)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.following = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.following.setReadOnly(True)
        self.following.setObjectName("following")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.following)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.followers = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.followers.setReadOnly(True)
        self.followers.setObjectName("followers")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.followers)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.fullname = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.fullname.setReadOnly(True)
        self.fullname.setObjectName("fullname")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fullname)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.bussinesAccount = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.bussinesAccount.setReadOnly(True)
        self.bussinesAccount.setObjectName("bussinesAccount")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bussinesAccount)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.externalUrl = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.externalUrl.setReadOnly(True)
        self.externalUrl.setObjectName("externalUrl")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.externalUrl)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.igtvCount = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.igtvCount.setReadOnly(True)
        self.igtvCount.setObjectName("igtvCount")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.igtvCount)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.biography = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.biography.setReadOnly(True)
        self.biography.setObjectName("biography")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.biography)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(430, 430, 861, 391))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.profilepost = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.profilepost.setReadOnly(True)
        self.profilepost.setObjectName("profilepost")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.profilepost)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.likes = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.likes.setReadOnly(True)
        self.likes.setObjectName("likes")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.likes)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.description = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.description.setReadOnly(True)
        self.description.setObjectName("description")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.description)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.commentCount = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.commentCount.setReadOnly(True)
        self.commentCount.setObjectName("commentCount")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.commentCount)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.desHashtag = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.desHashtag.setReadOnly(True)
        self.desHashtag.setObjectName("desHashtag")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.desHashtag)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.postDate = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.postDate.setReadOnly(True)
        self.postDate.setObjectName("postDate")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.postDate)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.links = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.links.setReadOnly(True)
        self.links.setObjectName("links")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.links)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.locationInfo = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.locationInfo.setReadOnly(True)
        self.locationInfo.setObjectName("locationInfo")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.locationInfo)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.postUrl = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.postUrl.setReadOnly(True)
        self.postUrl.setObjectName("postUrl")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.postUrl)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.videoDuration = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.videoDuration.setReadOnly(True)
        self.videoDuration.setObjectName("videoDuration")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.videoDuration)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.videoViews = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.videoViews.setReadOnly(True)
        self.videoViews.setObjectName("videoViews")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.videoViews)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(430, 370, 151, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(430, 350, 211, 20))
        self.label_19.setObjectName("label_19")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 690, 401, 131))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "INSTAGRAM USER INFO APP"))
        self.uNameBtn.setText(_translate("MainWindow", "info"))
        self.usernamelabel.setText(_translate("MainWindow", "User Name"))
        self.MediaCount.setText(_translate("MainWindow", "Media Count"))
        self.label_2.setText(_translate("MainWindow", "Is Private"))
        self.label_3.setText(_translate("MainWindow", "following"))
        self.label_4.setText(_translate("MainWindow", "followers"))
        self.label_5.setText(_translate("MainWindow", "full name"))
        self.label_6.setText(_translate("MainWindow", "business account"))
        self.label_7.setText(_translate("MainWindow", "external Url"))
        self.label_8.setText(_translate("MainWindow", "IGTV Count"))
        self.label_16.setText(_translate("MainWindow", "biography"))
        self.label_15.setText(_translate("MainWindow", "profile post"))
        self.label_14.setText(_translate("MainWindow", "likes"))
        self.label_13.setText(_translate("MainWindow", "description"))
        self.label_12.setText(_translate("MainWindow", "comments"))
        self.label_9.setText(_translate("MainWindow", "description hashtag"))
        self.label_11.setText(_translate("MainWindow", "Last post date"))
        self.label_10.setText(_translate("MainWindow", "link"))
        self.label_20.setText(_translate("MainWindow", "Location"))
        self.label_21.setText(_translate("MainWindow", "image Link"))
        self.label_22.setText(_translate("MainWindow", "post video duration"))
        self.label_23.setText(_translate("MainWindow", "video views"))
        self.label_18.setText(_translate("MainWindow", "Last post details"))
        self.label_19.setText(_translate("MainWindow", "if account is private = no"))
        self.label.setText(_translate("MainWindow", "ABDUSSAMET KARADENIZ"))
        
        self.uNameBtn.clicked.connect(self.run)
       
    def run(self):

        username = self.usernameInput.text()
        insta = instaloader.Instaloader() 
        profile = instaloader.Profile.from_username(insta.context,username)
        
        #user infos
        self.followers.setText(str(profile.followers))
        self.igtvCount.setText(str(profile.igtvcount))
        self.externalUrl.setText(str(profile.external_url))
        self.mediaCount.setText(str(profile.mediacount))
        self.fullname.setText(str(profile.full_name))
        self.biography.setText(str(profile.biography))
        self.following.setText(str(profile.followees))

        if profile.is_business_account==True:
            self.bussinesAccount.setText("yes")
        else:
            self.bussinesAccount.setText("no")

        if profile.is_private==True:
            self.isPrivate.setText("yes")
        else:
            self.isPrivate.setText("no")
           
        #last post infos     
        if profile.is_private==False:
            posts = profile.get_posts()
            for post in posts:
                self.postDate.setText(str(post.date))
                self.mediaCount.setText(str(post.mediacount))
                self.likes.setText(str(post.likes))
                self.description.setText(str(post.caption))
                self.desHashtag.setText(str(post.caption_hashtags))
                self.commentCount.setText(str(post.comments))
                self.links.setText(str(post.url))
                self.locationInfo.setText(str(post.location))
                self.videoDuration.setText(str(post.video_duration))
                self.videoViews.setText(str(post.video_view_count))
                break
          
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
